# Configuración de Base de Datos PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-solitary-shadow-ahsnwm6p-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vi8IjU0srEPt
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# CONFIGURACIÓN DEL PUERTOoo
# ===============================
server.port=8080



spring.mail.host=imap.gmail.com
spring.mail.port=993
spring.mail.username=igonzalez@codigoagil.cl
spring.mail.password=yjrd btxv sigf smds
spring.mail.properties.mail.imap.ssl.enable=true
spring.mail.properties.mail.imaps.partialfetch=false
mail.imap.idle=true